const state = {
    taskList: [
        {
            taskName: "1: flagged and next",
            indent: 0,
            done: false,
            startDate: new Date("2018-11-10T21:51:40.598Z"),
            dueDate: new Date("2018-11-10T21:51:40.598Z"),
            completedDate: null,
            flagged: false,
            forceNext: true,
            isNext: true,
            notDroppable: false,
            tags: [],
            importance: 0,
            id: 435353245,
            taskIndexInMainList: null
        },
        {
            taskName: "2: Has flag",
            indent: 0,
            done: false,
            startDate: new Date("2018-11-10T21:51:40.598Z"),
            dueDate: new Date("2018-11-18T21:51:40.598Z"),
            completedDate: null,
            flagged: true,
            forceNext: false,
            isNext: false,
            notDroppable: false,
            tags: ["Hello"],
            importance: 0,
            id: 245325432543253,
            taskIndexInMainList: null
        },
        {
            taskName: "3: I have 2 children",
            indent: 0,
            done: false,
            startDate: new Date("2018-11-10T21:51:40.598Z"),
            dueDate: new Date("2018-11-25T21:51:40.598Z"),
            completedDate: null,
            flagged: false,
            forceNext: false,
            isNext: false,
            notDroppable: false,
            tags: [],
            importance: 0,
            id: 423525435534,
            taskIndexInMainList: null
        },
        {
            taskName: "3.1 Child uno",
            indent: 1,
            done: false,
            startDate: new Date("2018-11-10T21:51:40.598Z"),
            dueDate: new Date("2018-11-25T21:51:40.598Z"),
            completedDate: null,
            flagged: false,
            forceNext: false,
            isNext: false,
            notDroppable: false,
            tags: [],
            importance: 0,
            id: 9234823432,
            taskIndexInMainList: null
        },
        {
            taskName: "3.2 Child due",
            indent: 1,
            done: false,
            startDate: new Date("2018-11-10T21:51:40.598Z"),
            dueDate: new Date("2018-11-28T21:51:40.598Z"),
            completedDate: null,
            flagged: false,
            forceNext: false,
            isNext: false,
            notDroppable: false,
            tags: [],
            importance: 0,
            id: 92384324832,
            taskIndexInMainList: null
        },
        {
            taskName: "4. I have 2 children",
            indent: 0,
            done: false,
            startDate: new Date("2018-11-10T21:51:40.598Z"),
            dueDate: new Date("2018-12-02T21:51:40.598Z"),
            completedDate: null,
            flagged: false,
            forceNext: false,
            isNext: false,
            notDroppable: false,
            tags: [],
            importance: 0,
            id: 235436546456,
            taskIndexInMainList: null
        },
        {
            taskName: "4.1 Child uno",
            indent: 1,
            done: false,
            startDate: new Date("2018-11-10T21:51:40.598Z"),
            dueDate: new Date("2018-12-18T21:51:40.598Z"),
            completedDate: null,
            flagged: false,
            forceNext: false,
            isNext: false,
            notDroppable: false,
            tags: ["Work", "Family", "Friends", "Home", "Evening"],
            importance: 0,
            id: 5262562456234,
            taskIndexInMainList: null
        },
        {
            taskName: "4.2 Child with tags",
            indent: 1,
            done: false,
            startDate: new Date("2018-11-10T21:51:40.598Z"),
            dueDate: new Date("2019-01-18T21:51:40.598Z"),
            completedDate: null,
            flagged: false,
            forceNext: false,
            isNext: false,
            notDroppable: false,
            tags: ["Work", "Family", "Friends", "Home", "Evening"],
            importance: 0,
            id: 5243549484874,
            taskIndexInMainList: null
        },
        {
            taskName: "5 indent",
            indent: 0,
            done: false,
            startDate: new Date("2019-01-10T21:51:40.598Z"),
            dueDate: new Date("2018-11-05T21:51:40.598Z"),
            completedDate: null,
            flagged: false,
            forceNext: false,
            isNext: false,
            notDroppable: false,
            tags: [],
            importance: 0,
            id: 4329324222393,
            taskIndexInMainList: null
        },
        {
            taskName: "6 Future start",
            indent: 0,
            done: false,
            startDate: new Date("2019-11-10T21:51:40.598Z"),
            dueDate: new Date("2018-11-05T21:51:40.598Z"),
            completedDate: null,
            flagged: false,
            forceNext: false,
            isNext: false,
            notDroppable: false,
            tags: [],
            importance: 0,
            id: 432932482393,
            taskIndexInMainList: null
        },
        {
            taskName: "7 done",
            indent: 0,
            done: true,
            startDate: new Date("2018-11-10T21:51:40.598Z"),
            dueDate: new Date("2018-11-05T21:51:40.598Z"),
            completedDate: null,
            flagged: false,
            forceNext: false,
            isNext: false,
            notDroppable: false,
            tags: [],
            importance: 0,
            id: 432932482333,
            taskIndexInMainList: null
        },
        {
            taskName: "Normal task",
            indent: 0,
            done: false,
            startDate: new Date("2018-11-10T21:51:40.598Z"),
            dueDate: new Date("2018-11-18T21:51:40.598Z"),
            completedDate: null,
            flagged: false,
            forceNext: false,
            isNext: false,
            notDroppable: false,
            tags: ["Hello"],
            importance: 0,
            id: 2458021432423453,
            taskIndexInMainList: null
        },
        {
            taskName: "Normal task",
            indent: 0,
            done: false,
            startDate: new Date("2018-11-10T21:51:40.598Z"),
            dueDate: new Date("2018-11-18T21:51:40.598Z"),
            completedDate: null,
            flagged: false,
            forceNext: false,
            isNext: false,
            notDroppable: false,
            tags: ["Hello"],
            importance: 0,
            id: 24532534623,
            taskIndexInMainList: null
        },
        {
            taskName: "Normal task",
            indent: 0,
            done: false,
            startDate: new Date("2018-11-10T21:51:40.598Z"),
            dueDate: new Date("2018-11-18T21:51:40.598Z"),
            completedDate: null,
            flagged: false,
            forceNext: false,
            isNext: false,
            notDroppable: false,
            tags: ["Hello"],
            importance: 0,
            id: 2451112423453,
            taskIndexInMainList: null
        },
        {
            taskName: "Normal task",
            indent: 0,
            done: false,
            startDate: new Date("2018-11-10T21:51:40.598Z"),
            dueDate: new Date("2018-11-18T21:51:40.598Z"),
            completedDate: null,
            flagged: false,
            forceNext: false,
            isNext: false,
            notDroppable: false,
            tags: ["Hello"],
            importance: 0,
            id: 2453250760,
            taskIndexInMainList: null
        },
        {
            taskName: "Normal task",
            indent: 0,
            done: false,
            startDate: new Date("2018-11-10T21:51:40.598Z"),
            dueDate: new Date("2018-11-18T21:51:40.598Z"),
            completedDate: null,
            flagged: false,
            forceNext: false,
            isNext: false,
            notDroppable: false,
            tags: ["Hello"],
            importance: 0,
            id: 2453223452723453,
            taskIndexInMainList: null
        },
        {
            taskName: "Normal task",
            indent: 0,
            done: false,
            startDate: new Date("2018-11-10T21:51:40.598Z"),
            dueDate: new Date("2018-11-18T21:51:40.598Z"),
            completedDate: null,
            flagged: false,
            forceNext: false,
            isNext: false,
            notDroppable: false,
            tags: ["Hello"],
            importance: 0,
            id: 24532587564,
            taskIndexInMainList: null
        },
        {
            taskName: "Normal task",
            indent: 0,
            done: false,
            startDate: new Date("2018-11-10T21:51:40.598Z"),
            dueDate: new Date("2018-11-18T21:51:40.598Z"),
            completedDate: null,
            flagged: false,
            forceNext: false,
            isNext: false,
            notDroppable: false,
            tags: ["Hello"],
            importance: 0,
            id: 245325674573453,
            taskIndexInMainList: null
        },
        {
            taskName: "Normal task",
            indent: 0,
            done: false,
            startDate: new Date("2018-11-10T21:51:40.598Z"),
            dueDate: new Date("2018-11-18T21:51:40.598Z"),
            completedDate: null,
            flagged: false,
            forceNext: false,
            isNext: false,
            notDroppable: false,
            tags: ["Hello"],
            importance: 0,
            id: 124234243023453,
            taskIndexInMainList: null
        },
        {
            taskName: "Normal task",
            indent: 0,
            done: false,
            startDate: new Date("2018-11-10T21:51:40.598Z"),
            dueDate: new Date("2018-11-18T21:51:40.598Z"),
            completedDate: null,
            flagged: false,
            forceNext: false,
            isNext: false,
            notDroppable: false,
            tags: ["Hello"],
            importance: 0,
            id: 24532542342,
            taskIndexInMainList: null
        },
        {
            taskName: "Normal task",
            indent: 0,
            done: false,
            startDate: new Date("2018-11-10T21:51:40.598Z"),
            dueDate: new Date("2018-11-18T21:51:40.598Z"),
            completedDate: null,
            flagged: false,
            forceNext: false,
            isNext: false,
            notDroppable: false,
            tags: ["Hello"],
            importance: 0,
            id: 245322134123453,
            taskIndexInMainList: null
        },
        {
            taskName: "Normal task",
            indent: 0,
            done: false,
            startDate: new Date("2018-11-10T21:51:40.598Z"),
            dueDate: new Date("2018-11-18T21:51:40.598Z"),
            completedDate: null,
            flagged: false,
            forceNext: false,
            isNext: false,
            notDroppable: false,
            tags: ["Hello"],
            importance: 0,
            id: 2453253632423453,
            taskIndexInMainList: null
        }
    ],
    activeTask: 5
};

const getters = {
    taskList: state => {
        return state.taskList
    },
    activeTask: state => {
        return state.activeTask
    }
}

const mutations = {
    SET_ACTIVE_TASK(state, taskindex) {
        state.activeTask = taskindex
    },
    SET_TASK_NAME(state, payload) {
        state.taskList[payload[0]].taskName = payload[1]
    },
    UPDATE_A_TASK(state, payload) {
        state.taskList[payload[0]][payload[1]] = payload[2] // 0 = index, 1=key, 2=value
    },
    UPDATE_WHOLE_LIST(state, payload) {
        state.taskList = payload
    }
}

export default {
    state,
    getters,
    mutations
}